### ISSUE TITLE
go get fails on Windows 7 (go version go1.4 windows/amd64)

### ISSUE THREAD

**Issue by hugows** [Shopify/go-lua#35]
I couldn't install the library by go getting it. I got the following errors:

C:\Users\hugo>go get github.com/Shopify/go-lua
# github.com/Shopify/go-lua
c:\users\hugo\go\src\github.com\Shopify\go-lua\base.go:12: undefined: CheckType
c:\users\hugo\go\src\github.com\Shopify\go-lua\base.go:23: undefined: MetaField
c:\users\hugo\go\src\github.com\Shopify\go-lua\base.go:24: undefined: CheckType
c:\users\hugo\go\src\github.com\Shopify\go-lua\base.go:41: undefined: CheckInteger
c:\users\hugo\go\src\github.com\Shopify\go-lua\base.go:42: undefined: CheckType
c:\users\hugo\go\src\github.com\Shopify\go-lua\base.go:95: undefined: CheckStackWithMessage
c:\users\hugo\go\src\github.com\Shopify\go-lua\base.go:101: undefined: Errorf
c:\users\hugo\go\src\github.com\Shopify\go-lua\base.go:326: undefined: SetFunctions
c:\users\hugo\go\src\github.com\Shopify\go-lua\bit32.go:32: undefined: CheckUnsigned
c:\users\hugo\go\src\github.com\Shopify\go-lua\bit32.go:43: undefined: CheckUnsigned
c:\users\hugo\go\src\github.com\Shopify\go-lua\bit32.go:43: too many errors

**Comment by kpashka** [comment]
+1

**Comment by fbogsany** [comment]
I don't have a Windows machine to test this on. The supposedly undefined functions are all defined in `aux.go`.

**Comment by kpashka** [comment]
@fbogsany, `AUX` is a reserved word in Windows. See https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx. Should I prepare a renaming pull-request?

**Comment by fbogsany** [comment]
@kpashka please do!

**Comment by kpashka** [comment]
@fbogsany, looks like it's not enough :(

```
$ go build
# github.com/Shopify/go-lua
E:\Projects\src\github.com\Shopify\go-lua\os.go:28: undefined: syscall.Getrusage
E:\Projects\src\github.com\Shopify\go-lua\os.go:28: undefined: syscall.RUSAGE_SELF
E:\Projects\src\github.com\Shopify\go-lua\os.go:29: rusage.Utime undefined (type syscall.Rusage has no field or method Utime)
E:\Projects\src\github.com\Shopify\go-lua\os.go:29: rusage.Stime undefined (type syscall.Rusage has no field or method Stime)
E:\Projects\src\github.com\Shopify\go-lua\os.go:29: rusage.Utime undefined (type syscall.Rusage has no field or method Utime)
E:\Projects\src\github.com\Shopify\go-lua\os.go:29: rusage.Stime undefined (type syscall.Rusage has no field or method Stime)
```

I think it's possible to create separate `os_windows.go` (with win-only build flag) without that `clock` RegistryFunction, but not quite sure - is it important part of library? Just started digging this.

**Comment by fbogsany** [comment]
@kpashka can you please test PR #40? I've renamed `aux.go` and extracted the clock function to separate platform-dependent files.

**Comment by kpashka** [comment]
@fbogsany thanks! build is ok, but `go test` fails. Probably, it's unrelated to this.

```
$ go test
6765
6765
6765
--- FAIL: TestLua (0.00s)
        vm_test.go:70: {attrib true}
        vm_test.go:94: 'attrib' failed: interface conversion: interface is nil, not *lua.luaClosure
        vm_test.go:70: {bitwise false}
        vm_test.go:94: 'bitwise' failed: interface conversion: interface is nil, not *lua.luaClosure
        vm_test.go:70: {closure false}
        vm_test.go:94: 'closure' failed: interface conversion: interface is nil, not *lua.luaClosure
        vm_test.go:70: {events false}
        vm_test.go:94: 'events' failed: interface conversion: interface is nil, not *lua.luaClosure
        vm_test.go:70: {goto false}
        vm_test.go:94: 'goto' failed: interface conversion: interface is nil, not *lua.luaClosure
        vm_test.go:70: {locals false}
        vm_test.go:94: 'locals' failed: interface conversion: interface is nil, not *lua.luaClosure
        vm_test.go:70: {math false}
        vm_test.go:94: 'math' failed: interface conversion: interface is nil, not *lua.luaClosure
        vm_test.go:70: {sort false}
        vm_test.go:94: 'sort' failed: interface conversion: interface is nil, not *lua.luaClosure
        vm_test.go:70: {strings false}
        vm_test.go:94: 'strings' failed: interface conversion: interface is nil, not *lua.luaClosure
FAIL
exit status 1
FAIL    github.com/kpashka/go-lua       0.092s
```

**Comment by fbogsany** [comment]
@kpashka I pushed a change for path separators in tests, which I think might be the problem. Can you please test #40 again?

**Comment by kpashka** [comment]
@fbogsany Sorry, looks like, previously, I've forgot to update submodule, so VM haven't found any files to handle. Now there are less errors:

```go
$ go test
6765
6765
6765
testing require
+
testing bitwise operations
+
+
OK
testing closures
+
OK
testing metatables
+
+
OK
OK
testing local variables and environments
+
OK
testing numbers and math lib
OK
testing (parts of) table library
testing unpack
testing pack
testing sort
testing strings and string library
+
+
+
+
+
testing large numbers for format
OK
--- FAIL: TestLua (0.53s)
        vm_test.go:71: {attrib true}
        vm_test.go:97: 'attrib' failed: interface conversion: interface is nil, not *lua.luaClosure
        vm_test.go:71: {bitwise false}
        vm_test.go:71: {closure false}
        vm_test.go:71: {events false}
        vm_test.go:71: {goto false}
        vm_test.go:71: {locals false}
        vm_test.go:71: {math false}
        vm_test.go:71: {sort false}
        vm_test.go:97: 'sort' failed: interface conversion: interface is nil, not *lua.luaClosure
        vm_test.go:71: {strings false}
FAIL
exit status 1
FAIL    github.com/kpashka/go-lua       1.197s
```

**Comment by fbogsany** [comment]
Thanks @kpashka. The attrib.lua test fails because it uses non-portable path names. sort.lua fails because it uses `os.clock()`. I've marked both as non-portable and disabled them on Windows for now. Please let me know if the latest push to #40 works for you.

**Comment by kpashka** [comment]
@fbogsany Works perfect. Thanks for explanations and fixes!

**Comment by fbogsany** [comment]
Thanks for the testing @kpashka !

**Comment by hugows** [comment]
Works for me too, thanks guys!
