### ISSUE TITLE
Channels and Goroutines?

### ISSUE THREAD

**Issue by dimiro1** [Shopify/go-lua#37]
How do you intend to support Channels and Goroutines?

**Comment by fbogsany** [comment]
We don't intend to add direct support for channels and goroutines in go-lua. Our use case has a separate `lua.State` per goroutine, with no shared Lua state. We'll probably implement [coroutine support](http://www.lua.org/manual/5.2/manual.html#6.2) and [`XMove`, `Yield`, and `YieldWithContinuation` APIs](http://www.lua.org/manual/5.2/manual.html#lua_xmove).

**Comment by dimiro1** [comment]
It makes sense to me.
