### ISSUE TITLE
os.getenv should return nil for a missing env var

### ISSUE THREAD

**Issue by fbogsany** [Shopify/go-lua#52]
According to the Lua reference manual, `os.getenv` should return `nil` if the env var doesn't exist. Instead it returns an empty string.

**Comment by fbogsany** [comment]
https://github.com/Shopify/go-lua/blob/master/os.go#L62

**Comment by JackyChiu** [comment]
Is this still an issue? Right now the function mapped to `getenv` is returning a `int` value

**Comment by fbogsany** [comment]
This was fixed. Closing.
