### ISSUE TITLE
XMove not implemented

### ISSUE THREAD

**Issue by wjh** [Shopify/go-lua#66]
I'm trying to use the debug module to limit things such as "while true do end" from hanging, yet I get an "XMove not implemented" error from [this](https://github.com/Shopify/go-lua/blob/master/debug.go#L544) line.

I was wondering what is up? If it's just something that needs doing I'd be willing to take a look if I was pointed in the right direction.

Thanks.

**Comment by fbogsany** [comment]
`XMove` is [`lua_xmove`](https://www.lua.org/manual/5.3/manual.html#lua_xmove) in the reference implementation of Lua. It moves values between different thread stacks. We haven't implemented coroutine support in `go-lua`, so we also haven't implemented `XMove`.

**Comment by wjh** [comment]
I see, thank you for clearing things up!

For future reference to anyone stumbling across this, you can use the Go API for debug hooks just fine, they just won't work from Lua :)
